### ISSUE TITLE
Failing Test Cases - Ubuntu 18.04 , Python 3.6.7

### ISSUE THREAD

**Issue by riaz** [facebookresearch/sumo-challenge#66]
The build was successfuul, but unfortunately i am unable to read data. 
I see a parrtern in the errors and all have to be in sumo/threedee.
Any pointers would be very helpful.

sumo.semantic.tests.project_converter_tests (unittest.loader._FailedTest) ... ERROR
sumo.semantic.tests.project_object_dict_tests (unittest.loader._FailedTest) ... ERROR
sumo.semantic.tests.project_object_tests (unittest.loader._FailedTest) ... ERROR
sumo.semantic.tests.project_scene_tests (unittest.loader._FailedTest) ... ERROR
sumo.threedee.tests.box_3d_tests (unittest.loader._FailedTest) ... ERROR
sumo.threedee.tests.compute_bbox_tests (unittest.loader._FailedTest) ... ERROR
sumo.threedee.tests.gltf_converter_tests (unittest.loader._FailedTest) ... ERROR
sumo.threedee.tests.gltf_model_tests (unittest.loader._FailedTest) ... ERROR
sumo.threedee.tests.gltf_tests (unittest.loader._FailedTest) ... ERROR
sumo.threedee.tests.mesh_tests (unittest.loader._FailedTest) ... ERROR
sumo.threedee.tests.model_sampler_tests (unittest.loader._FailedTest) ... ERROR
sumo.threedee.tests.point_cloud_tests (unittest.loader._FailedTest) ... ERROR
sumo.threedee.tests.textured_mesh_tests (unittest.loader._FailedTest) ... ERROR
sumo.threedee.tests.voxel_grid_tests (unittest.loader._FailedTest) ... ERROR
sumo.threedee.tests.voxelizer_tests (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: sumo.images.tests.rgbdci_360_tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: sumo.images.tests.rgbdci_360_tests
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/images/tests/rgbdci_360_tests.py", line 17, in <module>
    from sumo.images.rgbdci_360 import Rgbdci360
  File "sumo/threedee/point_cloud.pxd", line 31, in init sumo.images.rgbdci_360
    cdef class PointCloud:
ImportError: /home/riaz/riaz/sumo-challenge/sumo-api/sumo/threedee/point_cloud.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2cv7imwriteERKNS_6StringERKNS_11_InputArrayERKSt6vectorIiSaIiEE

======================================================================
ERROR: sumo.metrics.tests.bb_evaluator_tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: sumo.metrics.tests.bb_evaluator_tests
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/metrics/tests/bb_evaluator_tests.py", line 17, in <module>
    from sumo.metrics.bb_evaluator import BBEvaluator
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/metrics/bb_evaluator.py", line 15, in <module>
    from sumo.metrics.evaluator import Evaluator
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/metrics/evaluator.py", line 19, in <module>
    from sumo.semantic.project_object_dict import ProjectObjectDict
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/semantic/project_object_dict.py", line 17, in <module>
    from sumo.semantic.project_object import ProjectObject
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/semantic/project_object.py", line 20, in <module>
    from sumo.threedee.box_3d import Box3d
ImportError: /home/riaz/riaz/sumo-challenge/sumo-api/sumo/threedee/box_3d.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2cv7imwriteERKNS_6StringERKNS_11_InputArrayERKSt6vectorIiSaIiEE

======================================================================
ERROR: sumo.metrics.tests.mesh_evaluator_tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: sumo.metrics.tests.mesh_evaluator_tests
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/metrics/tests/mesh_evaluator_tests.py", line 28, in <module>
    from sumo.semantic.project_scene import ProjectScene
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/semantic/project_scene.py", line 14, in <module>
    from sumo.semantic.project_object_dict import ProjectObjectDict
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/semantic/project_object_dict.py", line 17, in <module>
    from sumo.semantic.project_object import ProjectObject
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/semantic/project_object.py", line 20, in <module>
    from sumo.threedee.box_3d import Box3d
ImportError: /home/riaz/riaz/sumo-challenge/sumo-api/sumo/threedee/box_3d.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2cv7imwriteERKNS_6StringERKNS_11_InputArrayERKSt6vectorIiSaIiEE

======================================================================
ERROR: sumo.metrics.tests.util_tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: sumo.metrics.tests.util_tests
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/metrics/tests/util_tests.py", line 17, in <module>
    from sumo.semantic.project_scene import ProjectScene
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/semantic/project_scene.py", line 14, in <module>
    from sumo.semantic.project_object_dict import ProjectObjectDict
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/semantic/project_object_dict.py", line 17, in <module>
    from sumo.semantic.project_object import ProjectObject
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/semantic/project_object.py", line 20, in <module>
    from sumo.threedee.box_3d import Box3d
ImportError: /home/riaz/riaz/sumo-challenge/sumo-api/sumo/threedee/box_3d.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2cv7imwriteERKNS_6StringERKNS_11_InputArrayERKSt6vectorIiSaIiEE

======================================================================
ERROR: sumo.metrics.tests.voxel_evaluator_tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: sumo.metrics.tests.voxel_evaluator_tests
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/metrics/tests/voxel_evaluator_tests.py", line 26, in <module>
    from sumo.metrics.evaluator import Evaluator
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/metrics/evaluator.py", line 19, in <module>
    from sumo.semantic.project_object_dict import ProjectObjectDict
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/semantic/project_object_dict.py", line 17, in <module>
    from sumo.semantic.project_object import ProjectObject
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/semantic/project_object.py", line 20, in <module>
    from sumo.threedee.box_3d import Box3d
ImportError: /home/riaz/riaz/sumo-challenge/sumo-api/sumo/threedee/box_3d.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2cv7imwriteERKNS_6StringERKNS_11_InputArrayERKSt6vectorIiSaIiEE

======================================================================
ERROR: sumo.semantic.tests.project_converter_tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: sumo.semantic.tests.project_converter_tests
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/semantic/tests/project_converter_tests.py", line 15, in <module>
    from sumo.semantic.project_converter import ProjectConverter
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/semantic/project_converter.py", line 14, in <module>
    from sumo.semantic.project_object import ProjectObject
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/semantic/project_object.py", line 20, in <module>
    from sumo.threedee.box_3d import Box3d
ImportError: /home/riaz/riaz/sumo-challenge/sumo-api/sumo/threedee/box_3d.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2cv7imwriteERKNS_6StringERKNS_11_InputArrayERKSt6vectorIiSaIiEE

======================================================================
ERROR: sumo.semantic.tests.project_object_dict_tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: sumo.semantic.tests.project_object_dict_tests
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/semantic/tests/project_object_dict_tests.py", line 16, in <module>
    from sumo.semantic.project_object import ProjectObject
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/semantic/project_object.py", line 20, in <module>
    from sumo.threedee.box_3d import Box3d
ImportError: /home/riaz/riaz/sumo-challenge/sumo-api/sumo/threedee/box_3d.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2cv7imwriteERKNS_6StringERKNS_11_InputArrayERKSt6vectorIiSaIiEE

======================================================================
ERROR: sumo.semantic.tests.project_object_tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: sumo.semantic.tests.project_object_tests
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/semantic/tests/project_object_tests.py", line 20, in <module>
    from sumo.semantic.project_object import ProjectObject
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/semantic/project_object.py", line 20, in <module>
    from sumo.threedee.box_3d import Box3d
ImportError: /home/riaz/riaz/sumo-challenge/sumo-api/sumo/threedee/box_3d.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2cv7imwriteERKNS_6StringERKNS_11_InputArrayERKSt6vectorIiSaIiEE

======================================================================
ERROR: sumo.semantic.tests.project_scene_tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: sumo.semantic.tests.project_scene_tests
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/semantic/tests/project_scene_tests.py", line 17, in <module>
    from sumo.semantic.project_object import ProjectObject
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/semantic/project_object.py", line 20, in <module>
    from sumo.threedee.box_3d import Box3d
ImportError: /home/riaz/riaz/sumo-challenge/sumo-api/sumo/threedee/box_3d.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2cv7imwriteERKNS_6StringERKNS_11_InputArrayERKSt6vectorIiSaIiEE

======================================================================
ERROR: sumo.threedee.tests.box_3d_tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: sumo.threedee.tests.box_3d_tests
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/threedee/tests/box_3d_tests.py", line 16, in <module>
    from sumo.threedee.box_3d import Box3d
ImportError: /home/riaz/riaz/sumo-challenge/sumo-api/sumo/threedee/box_3d.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2cv7imwriteERKNS_6StringERKNS_11_InputArrayERKSt6vectorIiSaIiEE

======================================================================
ERROR: sumo.threedee.tests.compute_bbox_tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: sumo.threedee.tests.compute_bbox_tests
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/threedee/tests/compute_bbox_tests.py", line 16, in <module>
    from sumo.threedee.compute_bbox import ComputeBbox
ImportError: /home/riaz/riaz/sumo-challenge/sumo-api/sumo/threedee/compute_bbox.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2cv7imwriteERKNS_6StringERKNS_11_InputArrayERKSt6vectorIiSaIiEE

======================================================================
ERROR: sumo.threedee.tests.gltf_converter_tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: sumo.threedee.tests.gltf_converter_tests
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/threedee/tests/gltf_converter_tests.py", line 18, in <module>
    from sumo.threedee.glb_converter import gltf2glb
ImportError: /home/riaz/riaz/sumo-challenge/sumo-api/sumo/threedee/glb_converter.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2cv7imwriteERKNS_6StringERKNS_11_InputArrayERKSt6vectorIiSaIiEE

======================================================================
ERROR: sumo.threedee.tests.gltf_model_tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: sumo.threedee.tests.gltf_model_tests
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/threedee/tests/gltf_model_tests.py", line 20, in <module>
    from sumo.threedee.gltf_model import GltfModel
ImportError: /home/riaz/riaz/sumo-challenge/sumo-api/sumo/threedee/gltf_model.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2cv7imwriteERKNS_6StringERKNS_11_InputArrayERKSt6vectorIiSaIiEE

======================================================================
ERROR: sumo.threedee.tests.gltf_tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: sumo.threedee.tests.gltf_tests
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/threedee/tests/gltf_tests.py", line 18, in <module>
    from sumo.threedee.gltf import TinyGLTF
ImportError: /home/riaz/riaz/sumo-challenge/sumo-api/sumo/threedee/gltf.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2cv7imwriteERKNS_6StringERKNS_11_InputArrayERKSt6vectorIiSaIiEE

======================================================================
ERROR: sumo.threedee.tests.mesh_tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: sumo.threedee.tests.mesh_tests
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/threedee/tests/mesh_tests.py", line 16, in <module>
    from sumo.threedee.mesh import Mesh
ImportError: /home/riaz/riaz/sumo-challenge/sumo-api/sumo/threedee/mesh.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2cv7imwriteERKNS_6StringERKNS_11_InputArrayERKSt6vectorIiSaIiEE

======================================================================
ERROR: sumo.threedee.tests.model_sampler_tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: sumo.threedee.tests.model_sampler_tests
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/threedee/tests/model_sampler_tests.py", line 16, in <module>
    from sumo.threedee.gltf_model import GltfModel
ImportError: /home/riaz/riaz/sumo-challenge/sumo-api/sumo/threedee/gltf_model.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2cv7imwriteERKNS_6StringERKNS_11_InputArrayERKSt6vectorIiSaIiEE

======================================================================
ERROR: sumo.threedee.tests.point_cloud_tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: sumo.threedee.tests.point_cloud_tests
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/threedee/tests/point_cloud_tests.py", line 12, in <module>
    from sumo.threedee.point_cloud import PointCloud
ImportError: /home/riaz/riaz/sumo-challenge/sumo-api/sumo/threedee/point_cloud.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2cv7imwriteERKNS_6StringERKNS_11_InputArrayERKSt6vectorIiSaIiEE

======================================================================
ERROR: sumo.threedee.tests.textured_mesh_tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: sumo.threedee.tests.textured_mesh_tests
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/threedee/tests/textured_mesh_tests.py", line 19, in <module>
    from sumo.threedee.box_3d import Box3d
ImportError: /home/riaz/riaz/sumo-challenge/sumo-api/sumo/threedee/box_3d.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2cv7imwriteERKNS_6StringERKNS_11_InputArrayERKSt6vectorIiSaIiEE

======================================================================
ERROR: sumo.threedee.tests.voxel_grid_tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: sumo.threedee.tests.voxel_grid_tests
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/threedee/tests/voxel_grid_tests.py", line 18, in <module>
    from sumo.threedee.box_3d import Box3d
ImportError: /home/riaz/riaz/sumo-challenge/sumo-api/sumo/threedee/box_3d.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2cv7imwriteERKNS_6StringERKNS_11_InputArrayERKSt6vectorIiSaIiEE

======================================================================
ERROR: sumo.threedee.tests.voxelizer_tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: sumo.threedee.tests.voxelizer_tests
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/threedee/tests/voxelizer_tests.py", line 16, in <module>
    from sumo.threedee.gltf_model import GltfModel
ImportError: /home/riaz/riaz/sumo-challenge/sumo-api/sumo/threedee/gltf_model.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2cv7imwriteERKNS_6StringERKNS_11_InputArrayERKSt6vectorIiSaIiEE

----------------------------------------------------------------------
Ran 67 tests in 0.195s

FAILED (errors=20)

**Comment by riaz** [comment]
I created a docker image, with the environment suggested for building sumo-api , and it works!
Was anyone able to setup sumo-api on Ubuntu 18.04?

**Comment by andriiD** [comment]
> I created a docker image, with the environment suggested for building sumo-api , and it works!
> Was anyone able to setup sumo-api on Ubuntu 18.04?

Could you share your dockerfile? Because the test_semantic_score fails even on my ubuntu 16.04 image

**Comment by nydragon** [comment]
I found it work by installing opencv from source on Ubuntu 18.04

**Comment by riaz** [comment]
@nydragon  Can you share which opencv version you installed? I still have issues
======================================================================
ERROR: sumo.threedee.tests.textured_mesh_tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: sumo.threedee.tests.textured_mesh_tests
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/threedee/tests/textured_mesh_tests.py", line 19, in <module>
    from sumo.threedee.box_3d import Box3d
ImportError: /home/riaz/riaz/sumo-challenge/sumo-api/sumo/threedee/box_3d.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2cv7imwriteERKNS_6StringERKNS_11_InputArrayERKSt6vectorIiSaIiEE


======================================================================
ERROR: sumo.threedee.tests.voxel_grid_tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: sumo.threedee.tests.voxel_grid_tests
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/threedee/tests/voxel_grid_tests.py", line 18, in <module>
    from sumo.threedee.box_3d import Box3d
ImportError: /home/riaz/riaz/sumo-challenge/sumo-api/sumo/threedee/box_3d.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2cv7imwriteERKNS_6StringERKNS_11_InputArrayERKSt6vectorIiSaIiEE


======================================================================
ERROR: sumo.threedee.tests.voxelizer_tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: sumo.threedee.tests.voxelizer_tests
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/riaz/riaz/sumo-challenge/sumo-api/sumo/threedee/tests/voxelizer_tests.py", line 16, in <module>
    from sumo.threedee.gltf_model import GltfModel
ImportError: /home/riaz/riaz/sumo-challenge/sumo-api/sumo/threedee/gltf_model.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2cv7imwriteERKNS_6StringERKNS_11_InputArrayERKSt6vectorIiSaIiEE


----------------------------------------------------------------------
Ran 67 tests in 0.217s

FAILED (errors=20)

**Comment by riaz** [comment]
@andriiD  

FROM ubuntu:16.04
RUN apt-get update
RUN apt-get install python3 -y
CMD ["/bin/bash"]

**Comment by nydragon** [comment]
I download the opencv 4 from github. Compiled with ubuntu 18.04.
